### ISSUE TITLE
cmake on mac

### ISSUE THREAD

**Issue by benji-bou** [kim2lux/emgb#1]
I tried to cmake this emulator on macOS Catalina v10.15.5
Expected generation of correct makefile

```shell
CMake Error at CMakeLists.txt:18 (add_subdirectory):
  The source directory

    /Users/benjaminbouachour/Privé/Projects/emgb/lib/googletest

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

**Comment by jdellinger-ledger** [comment]
Did you operate: git submodule init --recursive before launching the cmake command ? Looks like there are no content if the google test folder :(

**Comment by kim2lux** [comment]
Did you operate: git submodule init --recursive before launching the cmake command ? Looks like there are no content if the google test folder :(

**Comment by benji-bou** [comment]
Thanks it soved my problem 
Maybe you should add this to the documentation for those like me who are not familiar with git submodule
